### ISSUE TITLE
Cyanogen Crashes hard

### ISSUE THREAD

**Issue by macdonst** [CreativeSDK/phonegap-plugin-csdk-asset-browser#9]
10-21 14:45:40.332 10316 10316 E AndroidRuntime: Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:com.cyngn.hexoicons, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo, com.android.systemui.navbar=overlay:com.cyngn.hexo}
10-21 14:45:40.332 10316 10316 E AndroidRuntime: java.lang.IncompatibleClassChangeError: com.adobe.creativesdk.foundation.internal.twowayview.ClickItemTouchListener$ItemClickGestureDetector
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at com.adobe.creativesdk.foundation.internal.twowayview.ClickItemTouchListener.<init>(ClickItemTouchListener.java:19)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at com.adobe.creativesdk.foundation.internal.twowayview.ItemClickSupport$TouchListener.<init>(ItemClickSupport.java:117)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at com.adobe.creativesdk.foundation.internal.twowayview.ItemClickSupport.<init>(ItemClickSupport.java:56)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at com.adobe.creativesdk.foundation.internal.twowayview.ItemClickSupport.addTo(ItemClickSupport.java:87)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at com.adobe.creativesdk.foundation.internal.storage.controllers.AdobeAssetsViewBaseRecyclerViewController.performInitialization(AdobeAssetsViewBaseRecyclerViewController.java:398)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at com.adobe.creativesdk.foundation.internal.storage.controllers.AdobeAssetsViewPhotoCollectionContainerFragment.setupAssetsDataSourceAndListViewControllers(AdobeAssetsViewPhotoCollectionContainerFragment.java:113)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at com.adobe.creativesdk.foundation.internal.storage.controllers.AdobeAssetViewBaseContainerFragment.onCreateView(AdobeAssetViewBaseContainerFragment.java:221)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.measureVertical(LinearLayout.java:898)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.View.measure(View.java:18799)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
10-21 14:45:40.332 10316 10316 E AndroidRuntime:    at android.widget.LinearLayout.measu
10-21 14:45:40.333  1487  1590 W ActivityManager:   Force finishing activity com.adobe.phonegap.confgram/com.adobe.creativesdk.foundation.internal.storage.controllers.AdobeUxAssetBrowserV2Activity
10-21 14:45:40.336  1487  1590 W ActivityManager:   Force finishing activity com.adobe.phonegap.confgram/com.adobe.phonegap.csdk.AssetBrowserActivity
10-21 14:45:40.350  5673  5673 D LogFetchServiceManager: Received entry added
10-21 14:45:40.378  1487  2638 I OpenGLRenderer: Initialized EGL, version 1.4
10-21 14:45:40.837  1487  1606 W ActivityManager: Activity pause timeout for ActivityRecord{8ced231 u0 com.adobe.phonegap.confgram/com.adobe.creativesdk.foundation.internal.storage.controllers.AdobeUxAssetBrowserV2Activity t5356 f}
10-21 14:45:43.062  4121  4837 D HeadsetStateMachine: Disconnected process mess

**Comment by macdonst** [comment]
Fixed as a dependent plugin was using an earlier version of the CSDK.
